<a href="https://colab.research.google.com/github/xoreo/md/blob/master/Automatic_Differentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Automatic/Algorithmic Differentiation
[Crude Notes](https://github.com/xoreo/md/blob/master/notes.pdf)

Some setup code

In [38]:
import numpy as np

N = 5
RANGE = (10, 20)
FUNC = lambda x: np.sin(x)

array([-0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

Now we need to calculate the function values to put in our vector.

In [39]:
def calc_func_vector(f, n, r):
  split_range = np.arange(r[0], r[1], (r[1]-r[0])/n)
  return np.array(list(map(f, split_range)))

array([-0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

Now that we made the vector, we need to construct the differentiation matrix.

In [0]:
def calc_D():
  D = np.zeros(shape=(N, N)) # Start off blank
  for i in range(len(D) - 1):
    D[i][i] = -1
    D[i][i+1] = 1
  D[N-1][0] = 1
  D[N-1][N-1] = -1
  return D

Put it all together

In [85]:
v = calc_func_vector(FUNC, N, RANGE)
D = calc_D()
p = D.dot(v)
print(p)


[ 0.00744819  1.52718027 -1.27851067 -0.46308393  0.20696614]
